### ISSUE TITLE
Tester les signaux pour les notifications sur les forums

### ISSUE THREAD

**Issue by GerardPaligot** [GerardPaligot/zds-site#19]
Les notifications de Zeste de Savoir sont calculées sur chaque page à partir de 2 modèles : `TopicFollowed` et `TopicRead`. A partir des sujets suivis par l'utilisateur, on peut connaitre les sujets qu'il a lu et ceux qu'il n'a pas lu.

Donc, les tests associés à `TopicFollowed` sont concentré dans le module du forum, avec une légère dépendance dans le module des tutoriels puisqu'un auteur suivra un sujet automatiquement à la mise en bêta de son contenu. 

Il faudra récupérer dans les tests fonctionnels des forums tous les asserts qui touchent à `TopicFollowed` et les migrer dans le module des notifications en attendant que les nouveaux tests avec les nouveaux modèles arrivent grâce à l'étape 2 de la ZEP-24.

**Comment by ChantyTaguan** [comment]
Idem que #22 pour les labels.

**Comment by GerardPaligot** [comment]
see https://github.com/GerardPaligot/zds-site/issues/28
