### ISSUE TITLE
Générer le fichier de migration pour TopicFollowed et le script de migration de ses données

### ISSUE THREAD

**Issue by GerardPaligot** [GerardPaligot/zds-site#20]
Je pensais que déplacer un modèle ne changeait pas sa table. Je me suis trompé. Il semblerait bien que la table se nommait `forum_topicfollowed` et qu'elle s'appelle maintenant `notification_topicfollowed` après le déplacement du modèle.

Il faut pusher le fichier de migration grâce à la commande `python manage.py makemigrations` et il faut écrire un fichier de migration des données pour copier les anciennes données du modèle vers le nouveau. Cependant, le script sera extrêmement simple puisque la structure du modèle n'a pas changé.

Je ping @artragis et @pierre-24. J'aimerais avoir un retour d'expérience de leur part concernant les scripts de migration des données. Je n'ai aucune expérience technique sur le sujet et je sais qu'ils ont fait des scripts de migration hautement plus complexe pour la ZEP-12. Merci à eux d'avance !

Merci à @artragis qui fournit une ressource qui pourrait correspondre tout à fait à notre problème : http://stackoverflow.com/questions/1258130/how-do-i-migrate-a-model-out-of-one-django-app-and-into-a-new-one

**Comment by artragis** [comment]
cela me parait étrange que la migration ne se contente pas de renommer.

Pour le reste, en terme de migration, on l'a fait à la sauvage car les 
tutos sont des objets spéciaux qui ont une double persistance (bdd/git) 
et qu'en plus on fusionnait tuto et article. Sinon, les migrations 
django fournissent une interface plutôt cool pour faire des migrations. 
En tout état de chose, on aurait dû nous même en passer par là mais 
notre outil était vraiment complexe et on a voulu travailler "à côté". 
C'est un tord, mais c'est comme ça.

**Comment by GerardPaligot** [comment]
Voici ce que Django m'a dit quand j'ai généré la migration:

```console
  0003_auto_20151119_2008.py:
    - Remove field topic from topicfollowed
    - Remove field user from topicfollowed
    - Delete model TopicFollowed
    - Alter field is_locked on topic
```

Et voici ce qu'il m'a dit quand j'ai effectué la migration sans faire aucune migration des données :

```console
  Applying forum.0003_auto_20151119_2008... OK
The following content types are stale and need to be deleted:

    forum | topicfollowed

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: yes
```

Sauf si je comprends mal les logs, il me semble pas qu'il renomme l'ancien modèle.

**Comment by artragis** [comment]
Ok je vois le genre.
je vais faire quelques recherches sur le net du coup. Mais je dois 
avouer que j'ai été trop bien habitué avec EntityFramework qui savait 
très bien faire un rename.

**Comment by GerardPaligot** [comment]
@artragis PR faite. Au final, j'ai trouvé la solution à mon problème par [là bas](http://stackoverflow.com/questions/25648393/how-to-move-a-model-between-two-django-apps-django-1-7/26472482#26472482).
