### ISSUE TITLE
Créer les signaux des contenus pour préparer l'étape 2

### ISSUE THREAD

**Issue by GerardPaligot** [GerardPaligot/zds-site#21]
Comment sont gérées les notifications sur les contenus actuels ? C'est assez rudimentaire pour l'instant. Nous avons d'abord ces [2 requêtes](https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/interventions.py#L80-L90). La première va récupérer la liste de toutes les réactions de l'utilisateur (oui, c'est un poil costaud). La seconde va récupérer tous les contenus lus mais avec une différence entre la dernière réaction lue par l'utilisateur et la dernière réaction sur le contenu. C'est à partir de ces 2 informations que nous calculons les notifications. Je rappel toujours que ces requêtes sont faites à chaque chargement de page.

Puisque le système actuel est rudimentaire, les contributions pour l'étape 1 le sont aussi :

- `mark_content_notification_read` : Marque un contenu et ses messages comme lu et retire la notification si elle existait. Il faut mettre à jour le modèle `ContentRead` pour sauvegarder la dernière réaction du tutoriel.
- `new_reaction_event` :  Envoi un évènement lorsqu'un membre poste une nouvelle réaction. Une notification doit s'afficher vers cette nouvelle réaction. Cependant, pour l'étape 1 de la ZEP, il ne sera pas nécessaire de faire grand-chose dans le `receiver` puisque les réactions ne fonctionnent par souscription comme le sont les sujets des forums.

**Comment by ChantyTaguan** [comment]
J'ai commencé à regarder ici. Je fais une PR pour que tu puisses suivre facilement, mais j'ai testé vite fait donc peut-être pas merger tout de suite.

**Comment by GerardPaligot** [comment]
Merci Taguan pour ta PR.
