### ISSUE TITLE
Tester les signaux pour les notifications sur les contenus

### ISSUE THREAD

**Issue by GerardPaligot** [GerardPaligot/zds-site#22]
D'après une rapide recherche sur le projet actuel grâce à pycharm, il existe que 2 asserts qui portent sur les notifications. Ces asserts se trouvent à [ces lignes](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/tests/tests_views.py#L4205-L4209) et il faudrait les extraire dans un test unitaire dans le module notification.

**Comment by ChantyTaguan** [comment]
Plutot "step-2", et pas "optional" pour les labels du coup. Non ?

**Comment by GerardPaligot** [comment]
Tout à fait, c'est changé !

**Comment by GerardPaligot** [comment]
see https://github.com/GerardPaligot/zds-site/issues/29
