### ISSUE TITLE
Créer les signaux des messages privés pour préparer l'étape 2

### ISSUE THREAD

**Issue by GerardPaligot** [GerardPaligot/zds-site#25]
Les messages privés se comportent quasiment comme les sujets des forums à l'exception près qu'il n'existe pas de `TopicFollowed` puisqu'un membre est d'office notifié à partir du moment où il se trouve parmi les auteurs d'une conversation privée.

- `mark_mp_notification_read` : Marque un MP et ses messages comme lu et retire la notification si elle existait.
- `new_message_event` :  Envoi un évènement lorsqu'un membre poste un nouveau message dans un MP. Une notification doit s'afficher dans la liste des MPs non lu et non pas dans la liste des notifications. Ceci pourrait être une évolution pour l'étape 3 mais il faut l'avis de la communauté !

**Comment by GerardPaligot** [comment]
J'ai un peu réfléchi à cette issue (entre 2 contributions de ZMessenger) et je me demande ce que nous pouvons faire (en tout cas pour le moment). Les MPs, c'est un peu comme des sujets d'un forum mais le suivi est différent. Nous suivons un message privé dès que nous figurons comme auteur ou comme participant.

A partir de là, nous avons 2 solutions :

- Soit la création d'un MP engendre **forcément** la création d'une subscription (dans les nouveaux modèles). Si on choisit cette solution, il y a pas grand chose à faire pour cette issue. Le code actuel ne fait que marquer des MPs comme lu et donc, ne concerne pas notre ZEP.
- Soit nous gardons la subscription basée sur la presence du membre dans les participants ou comme auteur, on doit faire un cas spécial pour les MPs avec les nouveaux modèles et il faut être attentif aux changements dans les participants et l'auteur pour enlever la subscription.

Qu'en pensez-vous ? @ChantyTaguan @Situphen

**Comment by ChantyTaguan** [comment]
Pas sûre de bien comprendre comment tu vois la solution 2. Pas de création d'un objet suscription pour les MPs ?

A priori, je préfère la solution 1, moins y a de cas particulier, mieux c'est.

**Comment by GerardPaligot** [comment]
Je ne suis pas sur de comprendre moi-même pour la solution 2 et je préfère la solution 1. Mais du coup, pour cette issue, il faut simplement créer des récepteurs de signaux qui font rien (dire dans les commentaires ce qu'ils feront dans l'étape 2) et les appeler dans les vues/mixins.

**Comment by ChantyTaguan** [comment]
C'est bizarrement fait les mark_read et autre PrivateTopicRead dis donc o_O

Tu es dessus ou je prépare une PR ? (pour ce soir ou demain je pense)

**Comment by GerardPaligot** [comment]
Au départ je voulais le faire mais la manière de faire m'a perturbé aussi et j'ai pas su trop quoi faire (d'où mon message plus haut). Je te laisse la main là dessus.
